# Generated by Django 6.0.5 on 2026-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_sal',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_city',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
