# Generated by Django 6.0.5 on 2026-05-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_employee_emp_name_remove_employee_emp_sal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_addr',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_city',
            new_name='City',
        ),
    ]
