# Generated by Django 6.0.5 on 2026-05-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_emp_addr_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='City',
            new_name='city',
        ),
    ]
