# Generated by Django 6.0.5 on 2026-05-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_address_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='city',
            new_name='City',
        ),
    ]
